export enum OrderStatusEnum {
    UNPAID = 'UNPAID',
    PAID = 'PAID',
    PROCESSING = 'PROCESSING',
    READY_FOR_PICKUP = 'READY_FOR_PICKUP',
    PICKED_UP = 'PICKED_UP',
    IN_DELIVERY = 'IN_DELIVERY',
    DELIVERED = 'DELIVERED',
    COMPLETED = 'COMPLETED',
    CANCELLED = 'CANCELLED',
}
